### ISSUE TITLE
您好，我复现了下您的代码，一直没有达到理想的想过想请假您一些问题？

### ISSUE THREAD

**Issue by XinMing0411** [wsntxxn/AudioCaption#1]
我最近复现了一下您的代码，核心代码都一样，都是从您DCASE2020的代码copy的，然后网络结构、参数跟您设置的一致、Encoder的预训练参数也是down的您的模型，但是实验结果一直很差，Spiderscore可能才0.18左右，想请教您一下原因，真的调了好久了

**Comment by XinMing0411** [comment]
您训练时loss好收敛么？我这训练时loss一直不太收敛

**Comment by wsntxxn** [comment]
由于exposure bias的存在，用lr scheduler不断减小学习率，loss降到3.6左右就不会往下了，否则validation上效果会变差

**Comment by wsntxxn** [comment]
你有微信之类的联系方式吗？加你详聊

**Comment by XinMing0411** [comment]
ok ok 太感谢了 wx:ZYM_BUPT_2014
