### ISSUE TITLE
Paper 

### ISSUE THREAD

**Issue by redrabbit94** [wsntxxn/AudioCaption#4]
Thanks for sharing, great work! Could you offer links to articles about this repo, and is it convenient to know if the repo contains the method you submitted in dcase 2022?

**Comment by wsntxxn** [comment]
Sorry for the procrastination, the codes and sample configuration files for reinforcement learning and ensemble have been uploaded.

**Comment by wsntxxn** [comment]
The audio-text contrastive learning code has also been uploaded to https://github.com/wsntxxn/DCASE2022T6_CLAP. You can refer to it.

**Comment by redrabbit94** [comment]
Thanks so much！Best wishes！

发自我的iPhone

在 2023年2月16日，11:14，Xuenan Xu ***@***.***> 写道：

﻿

The audio-text contrastive learning code has also been uploaded to https://github.com/wsntxxn/DCASE2022T6_CLAP. You can refer to it.
